/* เฉลยอ้างอิงของทุกด่านในคอร์ส Python (ใช้ทดสอบตัวตรวจ) */
module.exports = {
  "print/0": 'print("สวัสดี Python")',
  "print/1": 'print("Python")\nprint("สนุก")\nprint("มาก")',
  "print/2": 'print("คะแนน:", 100)',
  "print/3": 'print(2026, "07", "09", sep="-")',
  "print/4": 'name = input()\nprint("สวัสดี", name)',
  "print/5": 'n = input()\nprint(int(n) + 10)',
  "print/6": 'price = 50\nprint("=== ใบเสร็จ ===")\nprint("กาแฟ", price, "บาท")\nprint("รวม", price, "บาท")',
  "print/7": 'w = int(input())\nh = int(input())\nprint("พื้นที่ =", w * h)',

  "variable/0": 'name = "มะลิ"\nprint("ฉันชื่อ", name)',
  "variable/1": 'hp = 80\npotion = 25\nprint(hp + potion)',
  "variable/2": 'coins = 10\ncoins += 8\ncoins -= 3\nprint(coins)',
  "variable/3": 'age = "12"\nprint(int(age) + 1)',
  "variable/4": 'level = 5\nprint(f"ตอนนี้เลเวล {level}")',
  "variable/5": 'a = 5\nb = 9\na, b = b, a\nprint(a)\nprint(b)',

  "datatype/0": 'print(type(3.14))',
  "datatype/1": 'print(7 / 2)\nprint(7 // 2)',
  "datatype/2": 'print(10 > 7)',
  "datatype/3": 'print(int(3.9))',
  "datatype/4": 'print(str(100) + "แต้ม")',

  "string/0": 'word = "victory"\nprint(word.upper())',
  "string/1": 'spell = "abrakadabra"\nprint(len(spell))',
  "string/2": 's = "python-master"\nprint(s[0:6])',
  "string/3": 'msg = "ฉันเกลียดบั๊ก"\nprint(msg.replace("เกลียด", "รัก"))',
  "string/4": 'data = "มะลิ,15,นักเวท"\nparts = data.split(",")\nprint(parts[2])',
  "string/5": 'song = "นานานา นา"\nprint(song.count("นา"))',
  "string/6": 'pwd = "abc123"\nif len(pwd) >= 8:\n    print("ผ่าน")\nelse:\n    print("สั้นเกินไป")',
  "string/7": 'word = "level"\nprint(word[::-1])\nprint(word == word[::-1])',

  "list/0": 'items = ["ดาบ", "โล่", "ยา"]\nprint(items[0])',
  "list/1": 'items = ["ดาบ", "โล่", "ยา"]\nitems.append("คบเพลิง")\nprint(len(items))',
  "list/2": 'items = ["ดาบ", "โล่", "ยา"]\nprint(items[-1])',
  "list/3": 'powers = [12, 30, 25]\nprint(sum(powers))',
  "list/4": 'items = ["ดาบ", "โล่", "ยา"]\nitems.remove("โล่")\nprint(len(items))',
  "list/5": 'nums = [30, 5, 12]\nnums.sort()\nprint(nums[0])',

  "tupleset/0": 'point = (10, 20)\nprint(point[0])',
  "tupleset/1": 'nums = (3, 6, 9, 12)\nprint(len(nums))',
  "tupleset/2": 'nums = [1, 2, 2, 3, 3, 3]\nprint(len(set(nums)))',
  "tupleset/3": 's = {1, 2, 3}\ns.add(4)\nprint(len(s))',
  "tupleset/4": 'a = {1, 2, 3}\nb = {2, 3, 4}\nprint(len(a & b))',

  "dict/0": 'player = {"name": "มะลิ", "hp": 100}\nprint(player["hp"])',
  "dict/1": 'player = {"name": "มะลิ", "hp": 100}\nplayer["mp"] = 50\nprint(player["mp"])',
  "dict/2": 'player = {"name": "มะลิ", "hp": 100}\nplayer["hp"] = 75\nprint(player["hp"])',
  "dict/3": 'player = {"name": "มะลิ", "hp": 100}\nprint("hp" in player)',
  "dict/4": 'player = {"name": "มะลิ", "hp": 100}\nprint(len(player))',

  "operator/0": 'print(17 % 5)\nprint(17 // 5)',
  "operator/1": 'print(2 ** 10)',
  "operator/2": 'print(True and False)\nprint(True or False)',
  "operator/3": 'print(3 in [1, 2, 3])',
  "operator/4": 'age = 15\nprint(10 <= age <= 18)',
  "operator/5": 'print(5 & 3)',

  "ifelse/0": 'key = 7\nif key > 5:\n    print("ประตูเปิด")\nelse:\n    print("ประตูล็อก")',
  "ifelse/1": 'score = 75\nif score >= 80:\n    print("A")\nelif score >= 70:\n    print("B")\nelse:\n    print("F")',
  "ifelse/2": 'hp = 50\nhas_key = True\nif hp > 0 and has_key:\n    print("ไปต่อ")\nelse:\n    print("ติดอยู่")',
  "ifelse/3": 'n = 7\nif n % 2 == 0:\n    print("คู่")\nelse:\n    print("คี่")',
  "ifelse/4": 'hp = 70\nlv = 12\nif hp > 50:\n    if lv > 10:\n        print("สู้บอส")\n    else:\n        print("ฝึกต่อ")',
  "ifelse/5": 'total = 1200\nif total >= 1000:\n    print(total * 0.8)\nelif total >= 500:\n    print(total * 0.9)\nelse:\n    print(total)',
  "ifelse/6": 'year = 2024\nif (year % 4 == 0 and year % 100 != 0) or year % 400 == 0:\n    print("อธิกสุรทิน")\nelse:\n    print("ปีปกติ")',

  "loop/0": 'for i in range(1, 6):\n    print("เก็บเหรียญที่", i)',
  "loop/1": 'total = 0\nfor i in range(1, 11):\n    total += i\nprint(total)',
  "loop/2": 'count = 3\nwhile count > 0:\n    print(count)\n    count -= 1\nprint("ทะยาน!")',
  "loop/3": 'for i in range(1, 11):\n    if i % 2 == 0:\n        print(i)',
  "loop/4": 'for i in range(1, 6):\n    if i == 3:\n        continue\n    print(i)',
  "loop/5": 'for i in range(3):\n    print("*" * 3)',
  "loop/6": 'for i in range(1, 6):\n    print(f"7 x {i} = {7 * i}")',
  "loop/7": 'for i in range(1, 5):\n    print("*" * i)',

  "flowchart/0": 'x = 10\nif x > 5:\n    print("มากกว่า")\nelse:\n    print("น้อยกว่า")',
  "flowchart/1": 'i = 1\nwhile i <= 3:\n    print("รอบที่", i)\n    i += 1\nprint("จบ")',
  "flowchart/2": 'total = 0\nfor i in range(1, 5):\n    total += i * 2\nprint(total)',
  "flowchart/3": 'scores = [40, 75, 60]\nbest = 0\nfor s in scores:\n    if s > best:\n        best = s\nprint(best)',

  "function/0": 'def greet():\n    print("สวัสดีนักผจญภัย")\n\ngreet()',
  "function/1": 'def double(x):\n    return x * 2\n\nprint(double(21))',
  "function/2": 'def attack(name, dmg):\n    print(name, "โจมตี", dmg)\n\nattack("อัศวิน", 30)',
  "function/3": 'def heal(amount=10):\n    return amount\n\nprint(heal())\nprint(heal(50))',
  "function/4": 'square = lambda x: x * x\nprint(square(6))',
  "function/5": 'import math\nprint(math.sqrt(144))',

  "exception/0": 'try:\n    x = 10 / 0\nexcept:\n    print("error")',
  "exception/1": 'try:\n    n = int("abc")\nexcept:\n    print("ไม่ใช่ตัวเลข")',
  "exception/2": 'try:\n    n = int("5")\nexcept:\n    print("error")\nfinally:\n    print("จบการทำงาน")',

  "oop/0": 'class Hero:\n    def __init__(self, name):\n        self.name = name\n\nh = Hero("มะลิ")\nprint(h.name)',
  "oop/1": 'class Hero:\n    def attack(self):\n        print("โจมตี!")\n\nh = Hero()\nh.attack()',
  "oop/2": 'class Hero:\n    def __init__(self, hp):\n        self.hp = hp\n\nh = Hero(100)\nprint(h.hp)',
  "oop/3": 'class Animal:\n    def sound(self):\n        print("...")\n\nclass Cat(Animal):\n    def sound(self):\n        print("เหมียว")\n\nCat().sound()',
  // ── หัวข้อทฤษฎีที่เล่นได้บนเครื่องเสมือน ──
  "filehandling/0": 'open("note.txt", "w", encoding="utf-8").write("สวัสดีไฟล์")\nprint(open("note.txt", encoding="utf-8").read())',
  "filehandling/1": 'lines = open("fruits.txt", encoding="utf-8").readlines()\nprint(len(lines))',
  "filehandling/2": 'with open("score.txt", encoding="utf-8") as f:\n    print(int(f.read()) + 10)',
  "filehandling/3": 'with open("log.txt", "a", encoding="utf-8") as f:\n    f.write("บันทึกสำเร็จ\\n")\nwith open("log.txt", encoding="utf-8") as f:\n    print(f.read())',
  "filehandling/4": 'import csv\n\nscores = []\nwith open("students.csv", encoding="utf-8") as f:\n    for row in csv.DictReader(f):\n        scores.append(int(row["score"]))\nprint(sum(scores) / len(scores))',

  "gui/0": 'import tkinter as tk\n\nroot = tk.Tk()\nroot.title("โปรแกรมแรกของฉัน")\nroot.geometry("300x200")\nroot.mainloop()',
  "gui/1": 'import tkinter as tk\n\nroot = tk.Tk()\nroot.title("ทักทาย")\ntk.Label(root, text="สวัสดี Tkinter", font=("Arial", 18)).pack()\nroot.mainloop()',
  "gui/2": 'import tkinter as tk\n\ndef on_click():\n    label.config(text="ถูกกดแล้ว!")\n\nroot = tk.Tk()\nlabel = tk.Label(root, text="ยังไม่ได้กด")\nlabel.pack()\ntk.Button(root, text="กดฉัน", command=on_click).pack()\nroot.mainloop()',
  "gui/3": 'import tkinter as tk\n\ndef greet():\n    result.config(text="สวัสดี " + entry.get())\n\nroot = tk.Tk()\nentry = tk.Entry(root)\nentry.pack()\nresult = tk.Label(root, text="")\nresult.pack()\ntk.Button(root, text="ทักทาย", command=greet).pack()\nroot.mainloop()',
  "gui/4": 'import tkinter as tk\n\nroot = tk.Tk()\nroot.title("ฟอร์มสมาชิก")\ntk.Label(root, text="ชื่อ").grid(row=0, column=0)\ntk.Entry(root).grid(row=0, column=1)\ntk.Label(root, text="อายุ").grid(row=1, column=0)\ntk.Entry(root).grid(row=1, column=1)\nroot.mainloop()',
  "gui/5": 'import tkinter as tk\n\nroot = tk.Tk()\nroot.title("เมนูเครื่องดื่ม")\nlb = tk.Listbox(root)\nlb.insert(tk.END, "กาแฟ", "ชาเย็น", "โกโก้")\nlb.pack()\nroot.mainloop()',
  "gui/6": 'import tkinter as tk\nfrom tkinter import messagebox\n\ndef save():\n    messagebox.showinfo("สำเร็จ", "บันทึกข้อมูลแล้ว")\n\nroot = tk.Tk()\ntk.Button(root, text="บันทึก", command=save).pack()\nroot.mainloop()',
  "gui/7": 'import tkinter as tk\n\nscore = 0\n\ndef add():\n    global score\n    score += 1\n    label.config(text=f"คะแนน: {score}")\n\nroot = tk.Tk()\nroot.title("ตัวนับคะแนน")\nlabel = tk.Label(root, text="คะแนน: 0")\nlabel.pack()\ntk.Button(root, text="+1", command=add).pack()\nroot.mainloop()',

  "database/0": 'import sqlite3\n\ncon = sqlite3.connect(":memory:")\ncur = con.cursor()\ncur.execute("CREATE TABLE students (name TEXT, score INTEGER)")\ncur.execute("INSERT INTO students VALUES (\'มะลิ\', 80)")\ncur.execute("INSERT INTO students VALUES (\'ฟ้า\', 92)")\nprint(cur.execute("SELECT COUNT(*) FROM students").fetchone()[0])',
  "database/1": 'import sqlite3\n\ncon = sqlite3.connect(":memory:")\ncur = con.cursor()\ncur.execute("CREATE TABLE students (name TEXT, score INTEGER)")\ncur.executemany("INSERT INTO students VALUES (?, ?)", [("มะลิ", 80), ("ฟ้า", 92), ("ใบเตย", 65)])\nfor row in cur.execute("SELECT name FROM students WHERE score >= 70 ORDER BY score DESC"):\n    print(row[0])',
  "database/2": 'import sqlite3\n\ncon = sqlite3.connect(":memory:")\ncur = con.cursor()\ncur.execute("CREATE TABLE students (name TEXT, score INTEGER)")\ncur.executemany("INSERT INTO students VALUES (?, ?)", [("มะลิ", 80), ("ฟ้า", 92)])\ncur.execute("UPDATE students SET score = 95 WHERE name = ?", ("มะลิ",))\ncon.commit()\nprint(cur.execute("SELECT score FROM students WHERE name = ?", ("มะลิ",)).fetchone()[0])',
  "database/3": 'import sqlite3\n\ncon = sqlite3.connect(":memory:")\ncur = con.cursor()\ncur.execute("CREATE TABLE students (name TEXT, score INTEGER)")\ncur.executemany("INSERT INTO students VALUES (?, ?)", [("มะลิ", 80), ("ฟ้า", 92), ("ใบเตย", 65)])\ncur.execute("DELETE FROM students WHERE score < 70")\nprint(cur.execute("SELECT COUNT(*) FROM students").fetchone()[0])',
  "database/4": 'import sqlite3\n\ncon = sqlite3.connect(":memory:")\ncur = con.cursor()\ncur.execute("CREATE TABLE products (name TEXT, price INTEGER)")\nname, price = "กาแฟ", 50\ncur.execute("INSERT INTO products VALUES (?, ?)", (name, price))\nrow = cur.execute("SELECT price FROM products WHERE name = ?", ("กาแฟ",)).fetchone()\nprint(row[0])',

  "webapp/0": 'from html.parser import HTMLParser\n\nhtml = "<html><head><title>ร้านกาแฟมะลิ</title></head><body><h1>เมนู</h1></body></html>"\n\nclass TitleParser(HTMLParser):\n    def __init__(self):\n        super().__init__()\n        self.in_title = False\n        self.title = ""\n    def handle_starttag(self, tag, attrs):\n        if tag == "title":\n            self.in_title = True\n    def handle_endtag(self, tag):\n        if tag == "title":\n            self.in_title = False\n    def handle_data(self, data):\n        if self.in_title:\n            self.title += data\n\np = TitleParser()\np.feed(html)\nprint(p.title)',
  "webapp/1": 'from html.parser import HTMLParser\n\nhtml = \'<nav><a href="/menu">เมนู</a><a href="/about">เกี่ยวกับ</a><a href="/contact">ติดต่อ</a></nav>\'\n\nclass LinkParser(HTMLParser):\n    def __init__(self):\n        super().__init__()\n        self.links = []\n    def handle_starttag(self, tag, attrs):\n        if tag == "a":\n            self.links.append(dict(attrs)["href"])\n\np = LinkParser()\np.feed(html)\nprint(len(p.links))\nprint(p.links[0])',

  "api/0": 'import json\n\nresponse = {"status": "ok", "count": 2}\nprint(json.dumps(response))',
  "api/1": 'import json\n\ntext = \'{"users": [{"name": "มะลิ"}, {"name": "ฟ้า"}]}\'\ndata = json.loads(text)\nprint(data["users"][1]["name"])',
  "api/2": 'def handle(path):\n    if path == "/hello":\n        return (200, "สวัสดี")\n    return (404, "ไม่พบ")\n\nprint(handle("/hello")[0])\nprint(handle("/abc")[0])',
  "api/3": 'def discount(price):\n    return price * 0.9\n\nassert discount(100) == 90\nassert discount(0) == 0\nprint("ผ่านทุกเทสต์")',

  "datascience/0": 'import statistics\n\nscores = [70, 80, 80, 90, 95]\nprint(statistics.mean(scores))\nprint(statistics.median(scores))\nprint(statistics.mode(scores))',
  "datascience/1": 'raw = [70, None, 85, -1, 90, None, 75]\nclean = [x for x in raw if x is not None and x >= 0]\nprint(sum(clean) / len(clean))',
  "datascience/2": 'x = [1, 2, 3, 4]\ny = [50, 60, 70, 80]\nmx = sum(x) / len(x)\nmy = sum(y) / len(y)\na = sum((xi - mx) * (yi - my) for xi, yi in zip(x, y)) / sum((xi - mx) ** 2 for xi in x)\nb = my - a * mx\nprint(a * 5 + b)',
};
