/* เฉลยอ้างอิงของทุกด่านในคอร์ส HTML / CSS / JavaScript (ใช้ทดสอบตัวตรวจ) */
module.exports = {
  /* ═══════════ HTML ═══════════ */
  "html:hbasic/0": `<h1>สวัสดีชาวเว็บ</h1>`,
  "html:hbasic/1": `<p>ยินดีต้อนรับ</p>\n<p>มาเรียน HTML กัน</p>`,
  "html:hbasic/2": `<!DOCTYPE html>\n<html>\n<head>\n  <title>เว็บแรกของฉัน</title>\n</head>\n<body>\n  <h1>หน้าแรก</h1>\n</body>\n</html>`,
  "html:hbasic/3": `<!DOCTYPE html>\n<html lang="th">\n<head>\n  <meta charset="UTF-8">\n  <title>ทดสอบ</title>\n</head>\n<body>\n  <p>ทดสอบภาษาไทย</p>\n</body>\n</html>`,
  "html:hbasic/4": `<p>พร้อมใช้งาน</p>\n<!-- <p>ยังไม่เสร็จ</p> -->`,
  "html:hbasic/5": `<p>ราคาพิเศษ <strong>ลด 50%</strong></p>`,

  "html:htext/0": `<h1>บทความของฉัน</h1>\n<h2>บทที่ 1</h2>\n<h3>หัวข้อย่อย</h3>`,
  "html:htext/1": `<p>บรรทัดหนึ่ง<br>บรรทัดสอง</p>`,
  "html:htext/2": `<p>ตอนที่ 1</p>\n<hr>\n<p>เรื่อง<strong>สำคัญ</strong></p>`,
  "html:htext/3": `<p>โปรโมชั่น <em>ห้ามพลาด</em> เฉพาะ <mark>วันนี้</mark> เท่านั้น</p>`,
  "html:htext/4": `<p>ราคา <del>1000</del> บาท เหลือ <ins>790</ins> บาท</p>`,
  "html:htext/5": `<p>ใช้ &lt;p&gt; &amp; &lt;div&gt;</p>`,
  "html:htext/6": `<blockquote>โค้ดที่ดีคือโค้ดที่อ่านง่าย</blockquote>\n<p>ใช้ <code>console.log</code> ตรวจค่า</p>`,

  "html:hlist/0": `<ul>\n  <li>กาแฟ</li>\n  <li>ชาเขียว</li>\n  <li>โกโก้</li>\n</ul>`,
  "html:hlist/1": `<ol>\n  <li>ต้มน้ำ</li>\n  <li>ใส่เส้น</li>\n  <li>ปรุงรส</li>\n</ol>`,
  "html:hlist/2": `<ul>\n  <li>เครื่องดื่ม\n    <ul>\n      <li>ร้อน</li>\n      <li>เย็น</li>\n    </ul>\n  </li>\n</ul>`,
  "html:hlist/3": `<dl>\n  <dt>HTML</dt>\n  <dd>ภาษามาร์กอัปสำหรับเว็บ</dd>\n</dl>`,
  "html:hlist/4": `<a href="https://www.google.com">ไปที่ Google</a>`,
  "html:hlist/5": `<a href="https://example.com" target="_blank" rel="noopener">เว็บตัวอย่าง</a>`,
  "html:hlist/6": `<a href="#summary">ไปหัวข้อสรุป</a>\n<h2 id="summary">สรุป</h2>`,

  "html:himg/0": `<img src="cat.jpg" alt="แมวส้ม">`,
  "html:himg/1": `<img src="banner.png" alt="แบนเนอร์" width="300" height="200">`,
  "html:himg/2": `<figure>\n  <img src="view.jpg" alt="วิวภูเขา">\n  <figcaption>ภาพถ่ายจากดอยอินทนนท์</figcaption>\n</figure>`,
  "html:himg/3": `<video src="clip.mp4" controls width="400"></video>`,
  "html:himg/4": `<iframe src="https://example.com" title="ตัวอย่างเว็บไซต์"></iframe>`,

  "html:htable/0": `<table>\n  <tr><td>มะลิ</td><td>15</td></tr>\n</table>`,
  "html:htable/1": `<table>\n  <tr><th>ชื่อ</th><th>อายุ</th></tr>\n  <tr><td>มะลิ</td><td>15</td></tr>\n</table>`,
  "html:htable/2": `<table>\n  <caption>รายชื่อนักเรียน</caption>\n  <thead>\n    <tr><th>ชื่อ</th><th>อายุ</th></tr>\n  </thead>\n  <tbody>\n    <tr><td>มะลิ</td><td>15</td></tr>\n  </tbody>\n</table>`,
  "html:htable/3": `<table>\n  <tr><th>ชื่อ</th><th>อายุ</th></tr>\n  <tr><td>มะลิ</td><td>15</td></tr>\n  <tr><td>ฟ้า</td><td>16</td></tr>\n  <tr><td colspan="2">รวมทั้งหมด 2 คน</td></tr>\n</table>`,
  "html:htable/4": `<table>\n  <tr><td rowspan="2">ม.3</td><td>มะลิ</td></tr>\n  <tr><td>ฟ้า</td></tr>\n</table>`,

  "html:hform/0": `<form>\n  <input type="text" name="username">\n</form>`,
  "html:hform/1": `<form>\n  <label for="email">อีเมล</label>\n  <input type="email" id="email" name="email">\n</form>`,
  "html:hform/2": `<form>\n  <input type="password" name="pwd">\n  <input type="number" name="age">\n</form>`,
  "html:hform/3": `<form>\n  <input type="radio" name="gender" value="male">\n  <input type="radio" name="gender" value="female">\n</form>`,
  "html:hform/4": `<form>\n  <select name="city">\n    <option value="bkk">กรุงเทพ</option>\n    <option value="cnx">เชียงใหม่</option>\n  </select>\n</form>`,
  "html:hform/5": `<form>\n  <textarea name="message" placeholder="พิมพ์ข้อความ"></textarea>\n  <button type="submit">ส่ง</button>\n</form>`,
  "html:hform/6": `<form>\n  <input type="email" name="email" required>\n  <input type="number" name="age" required min="1" max="120">\n  <button type="submit">สมัคร</button>\n</form>`,
  "html:hform/7": `<form>\n  <label for="uname">ชื่อผู้ใช้</label>\n  <input type="text" id="uname" name="username" required>\n  <input type="email" name="email" required>\n  <select name="plan">\n    <option value="free">ฟรี</option>\n    <option value="pro">โปร</option>\n  </select>\n  <button type="submit">สมัคร</button>\n</form>`,

  "html:hsem/0": `<header>\n  <h1>ร้านกาแฟ</h1>\n  <nav>\n    <a href="#">หน้าแรก</a>\n    <a href="#">เมนู</a>\n  </nav>\n</header>`,
  "html:hsem/1": `<main>\n  <article>\n    <h2>เมล็ดกาแฟคั่วใหม่</h2>\n    <p>หอมกรุ่นทุกเช้า</p>\n  </article>\n</main>`,
  "html:hsem/2": `<aside>โปรโมชั่นเดือนนี้</aside>\n<footer>&copy; 2026 ร้านกาแฟ</footer>`,
  "html:hsem/3": `<div id="hero">แบนเนอร์</div>\n<p class="note">ข้อความหนึ่ง</p>\n<p class="note">ข้อความสอง</p>`,
  "html:hsem/4": `<!DOCTYPE html>\n<html lang="th">\n<head>\n  <meta charset="UTF-8">\n  <meta name="viewport" content="width=device-width, initial-scale=1.0">\n  <meta name="description" content="ร้านกาแฟคั่วสดใจกลางเมือง">\n  <title>ร้านกาแฟ</title>\n</head>\n<body>\n  <h1>ร้านกาแฟ</h1>\n</body>\n</html>`,
  "html:hsem/5": `<!DOCTYPE html>\n<html lang="th">\n<head>\n  <meta charset="UTF-8">\n  <title>บล็อกของฉัน</title>\n</head>\n<body>\n  <header><h1>บล็อกของฉัน</h1></header>\n  <nav><a href="#">หน้าแรก</a></nav>\n  <main>\n    <article>\n      <h2>โพสต์แรก</h2>\n      <p>สวัสดีทุกคน</p>\n    </article>\n  </main>\n  <footer>ติดต่อ: mali@example.com</footer>\n</body>\n</html>`,

  "html:hadv/0": `<button data-product-id="42" data-price="250">ซื้อเลย</button>`,
  "html:hadv/1": `<button aria-label="ปิดหน้าต่าง">✕</button>`,
  "html:hadv/2": `<!DOCTYPE html>\n<html lang="th">\n<head>\n  <meta charset="UTF-8">\n  <title>เว็บของฉัน</title>\n  <link rel="stylesheet" href="style.css">\n  <script src="app.js" defer></script>\n</head>\n<body>\n  <h1>หน้าแรก</h1>\n</body>\n</html>`,
  "html:hadv/3": `<details>\n  <summary>คำถามที่พบบ่อย</summary>\n  <p>เราส่งของทุกวันจันทร์</p>\n</details>`,
  "html:hadv/4": `<article class="card">\n  <img src="mali.jpg" alt="รูปโปรไฟล์">\n  <h2>มะลิ นักพัฒนาเว็บ</h2>\n  <ul>\n    <li>HTML</li>\n    <li>CSS</li>\n  </ul>\n  <a href="mailto:mali@example.com">ส่งอีเมล</a>\n</article>`,

  /* ═══════════ CSS ═══════════ */
  "css:cssbasic/0": `h1 { color: blue; }`,
  "css:cssbasic/1": `h1 {\n  color: #e74c3c;\n  font-size: 40px;\n}\np {\n  color: gray;\n}`,
  "css:cssbasic/2": `.warn {\n  color: orange;\n  font-weight: bold;\n}`,
  "css:cssbasic/3": `#hero {\n  background-color: #2c3e50;\n  color: white;\n  padding: 20px;\n}`,
  "css:cssbasic/4": `body {\n  font-family: Arial, sans-serif;\n  color: #333333;\n}`,
  "css:cssbasic/5": `.note {\n  color: green;\n  /* background-color: red; */\n}`,

  "css:csstext/0": `h1 {\n  color: #ffffff;\n  background-color: #8e44ad;\n}`,
  "css:csstext/1": `.glass {\n  background-color: rgba(0, 0, 0, 0.5);\n}`,
  "css:csstext/2": `body {\n  font-family: Kanit, Arial, sans-serif;\n  font-size: 18px;\n}`,
  "css:csstext/3": `h2 {\n  text-align: center;\n}\n.lead {\n  font-weight: 700;\n  font-style: italic;\n}`,
  "css:csstext/4": `p {\n  line-height: 1.7;\n  letter-spacing: 0.5px;\n}`,
  "css:csstext/5": `.btn {\n  text-decoration: none;\n  text-transform: uppercase;\n  color: #2980b9;\n}`,

  "css:cssbox/0": `.box {\n  width: 200px;\n  padding: 16px;\n  background-color: #ecf0f1;\n}`,
  "css:cssbox/1": `.card {\n  border: 2px solid #34495e;\n  border-radius: 12px;\n}`,
  "css:cssbox/2": `.box {\n  margin: 20px 10px;\n}`,
  "css:cssbox/3": `.wrap {\n  width: 300px;\n  margin: 0 auto;\n}`,
  "css:cssbox/4": `* {\n  box-sizing: border-box;\n}\n.btn {\n  width: 150px;\n  padding: 12px;\n  border: 3px solid black;\n}`,
  "css:cssbox/5": `.tag {\n  display: inline-block;\n  padding: 4px 10px;\n}\n.hide {\n  display: none;\n}`,

  "css:csssel/0": `nav a {\n  background-color: #e67e22;\n  padding: 6px 12px;\n}`,
  "css:csssel/1": `h1, h2, h3 {\n  color: #16a085;\n}`,
  "css:csssel/2": `li:nth-child(even) {\n  background-color: #f0f0f0;\n}\nli:first-child {\n  font-weight: bold;\n}`,
  "css:csssel/3": `.btn {\n  background-color: #3498db;\n  color: white;\n  padding: 10px 20px;\n  text-decoration: none;\n}\n.btn:hover {\n  background-color: #2c3e50;\n}`,
  "css:csssel/4": `.req::after {\n  content: " *";\n  color: red;\n}\ninput[type="email"] {\n  border: 1px solid #27ae60;\n}`,
  "css:csssel/5": `p {\n  color: blue;\n}\n.text {\n  color: green;\n}\n#special {\n  color: #c0392b;\n}`,

  "css:cssflex/0": `.row {\n  display: flex;\n  gap: 12px;\n}`,
  "css:cssflex/1": `.bar {\n  display: flex;\n  justify-content: space-between;\n  align-items: center;\n}`,
  "css:cssflex/2": `.hero {\n  height: 200px;\n  display: flex;\n  justify-content: center;\n  align-items: center;\n}`,
  "css:cssflex/3": `.col {\n  display: flex;\n  flex-direction: column;\n  gap: 8px;\n}`,
  "css:cssflex/4": `.cards {\n  display: flex;\n  flex-wrap: wrap;\n  gap: 10px;\n}\n.card {\n  width: 45%;\n}`,
  "css:cssflex/5": `.layout {\n  display: flex;\n}\n.side {\n  width: 200px;\n}\n.content {\n  flex: 1;\n}`,
  "css:cssflex/6": `.pricing {\n  display: flex;\n  gap: 16px;\n  align-items: flex-start;\n}\n.plan {\n  flex: 1;\n  padding: 24px;\n}`,

  "css:cssgrid/0": `.grid {\n  display: grid;\n  grid-template-columns: 1fr 1fr 1fr;\n  gap: 10px;\n}`,
  "css:cssgrid/1": `.grid {\n  display: grid;\n  grid-template-columns: repeat(4, 1fr);\n  gap: 8px;\n}`,
  "css:cssgrid/2": `.grid {\n  display: grid;\n  grid-template-columns: 1fr 1fr;\n}\n.wide {\n  grid-column: span 2;\n}`,
  "css:cssgrid/3": `.gallery {\n  display: grid;\n  grid-template-columns: repeat(auto-fit, minmax(150px, 1fr));\n  gap: 12px;\n}`,
  "css:cssgrid/4": `.page {\n  display: grid;\n  grid-template-columns: 200px 1fr;\n  gap: 10px;\n}\n.hd, .ft {\n  grid-column: span 2;\n}`,

  "css:csspos/0": `.box {\n  position: relative;\n  top: 20px;\n  left: 30px;\n}`,
  "css:csspos/1": `.card {\n  position: relative;\n  padding: 20px;\n}\n.badge {\n  position: absolute;\n  top: 0;\n  right: 0;\n}`,
  "css:csspos/2": `.topbar {\n  position: fixed;\n  top: 0;\n  left: 0;\n  width: 100%;\n  z-index: 100;\n}`,
  "css:csspos/3": `.back {\n  position: relative;\n  z-index: 1;\n}\n.front {\n  position: relative;\n  z-index: 10;\n}`,
  "css:csspos/4": `.scrollbox {\n  height: 80px;\n  overflow: auto;\n  border: 1px solid gray;\n}`,

  "css:cssadv/0": `:root {\n  --primary: #7b5cf0;\n}\n.btn {\n  background-color: var(--primary);\n  color: white;\n  padding: 10px 20px;\n}`,
  "css:cssadv/1": `.card {\n  box-shadow: 0 4px 12px rgba(0,0,0,0.15);\n  border-radius: 16px;\n  padding: 20px;\n}`,
  "css:cssadv/2": `.hero {\n  background: linear-gradient(to right, #7b5cf0, #3498db);\n  height: 150px;\n  color: white;\n}`,
  "css:cssadv/3": `.btn {\n  transition: all 0.3s ease;\n}\n.btn:hover {\n  transform: scale(1.1);\n}`,
  "css:cssadv/4": `@keyframes fadeIn {\n  from { opacity: 0; }\n  to { opacity: 1; }\n}\n.pulse {\n  animation: fadeIn 2s ease infinite;\n}`,
  "css:cssadv/5": `.menu {\n  display: flex;\n}\n@media (max-width: 600px) {\n  .menu { display: none; }\n}`,
  "css:cssadv/6": `:root {\n  --card-bg: #ffffff;\n}\n.profile {\n  display: flex;\n  gap: 16px;\n  align-items: center;\n  padding: 20px;\n  border-radius: 16px;\n  box-shadow: 0 4px 12px rgba(0,0,0,0.15);\n  background: var(--card-bg);\n}`,

  /* ═══════════ JavaScript ═══════════ */
  "js:jsbasic/0": `console.log("สวัสดี JavaScript");`,
  "js:jsbasic/1": `let score = 10;\nscore = 25;\nconsole.log(score);`,
  "js:jsbasic/2": `const PI = 3.14;\nconsole.log(PI * 10 * 10);`,
  "js:jsbasic/3": `console.log(typeof "มะลิ");\nconsole.log(typeof 25);\nconsole.log(typeof true);`,
  "js:jsbasic/4": `const name = "มะลิ";\nconst age = 15;\nconsole.log(\`สวัสดี \${name} อายุ \${age} ปี\`);`,
  "js:jsbasic/5": `const a = "10";\nconst b = "5";\nconsole.log(a + b);\nconsole.log(Number(a) + Number(b));`,

  "js:jsop/0": `console.log(17 % 5);\nconsole.log(2 ** 10);\nconsole.log(7 / 2);`,
  "js:jsop/1": `console.log("5" == 5);\nconsole.log("5" === 5);`,
  "js:jsop/2": `const score = 75;\nif (score >= 80) {\n  console.log("A");\n} else if (score >= 70) {\n  console.log("B");\n} else if (score >= 60) {\n  console.log("C");\n} else {\n  console.log("F");\n}`,
  "js:jsop/3": `let username = "";\nconsole.log(username || "ผู้เยี่ยมชม");`,
  "js:jsop/4": `const age = 20;\nconsole.log(age >= 18 ? "ผู้ใหญ่" : "เยาวชน");`,
  "js:jsop/5": `const day = 3;\nswitch (day) {\n  case 1: console.log("จันทร์"); break;\n  case 2: console.log("อังคาร"); break;\n  case 3: console.log("พุธ"); break;\n  default: console.log("ไม่ทราบ");\n}`,

  "js:jsloop/0": `for (let i = 1; i <= 5; i++) {\n  console.log(i);\n}`,
  "js:jsloop/1": `let sum = 0;\nfor (let i = 1; i <= 100; i++) {\n  sum += i;\n}\nconsole.log(sum);`,
  "js:jsloop/2": `let n = 3;\nwhile (n > 0) {\n  console.log(n);\n  n--;\n}\nconsole.log("เริ่ม!");`,
  "js:jsloop/3": `for (let i = 1; i <= 10; i++) {\n  if (i === 3) continue;\n  if (i === 6) break;\n  console.log(i);\n}`,
  "js:jsloop/4": `const fruits = ["แอปเปิล", "กล้วย", "ส้ม"];\nfor (const f of fruits) {\n  console.log(f);\n}`,

  "js:jsfunc/0": `function greet() {\n  console.log("สวัสดีชาวโลก");\n}\ngreet();`,
  "js:jsfunc/1": `function add(a, b) {\n  return a + b;\n}\nconsole.log(add(7, 5));`,
  "js:jsfunc/2": `function greet(name = "ผู้เยี่ยมชม") {\n  return \`สวัสดี \${name}\`;\n}\nconsole.log(greet());\nconsole.log(greet("มะลิ"));`,
  "js:jsfunc/3": `const double = (x) => x * 2;\nconsole.log(double(21));`,
  "js:jsfunc/4": `let x = 10;\nfunction test() {\n  let x = 99;\n  console.log(x);\n}\ntest();\nconsole.log(x);`,
  "js:jsfunc/5": `function repeat(n, fn) {\n  for (let i = 0; i < n; i++) {\n    fn();\n  }\n}\nrepeat(3, () => console.log("ทำ"));`,

  "js:jsarray/0": `const fruits = ["แอปเปิล", "กล้วย", "ส้ม"];\nconsole.log(fruits[0]);\nconsole.log(fruits.length);`,
  "js:jsarray/1": `const fruits = ["แอปเปิล", "กล้วย"];\nfruits.push("มะม่วง");\nfruits.pop();\nconsole.log(fruits.length);`,
  "js:jsarray/2": `const nums = [1, 2, 3, 4];\nconst doubled = nums.map(x => x * 2);\nconsole.log(doubled.join(","));`,
  "js:jsarray/3": `const scores = [45, 80, 30, 95];\nconsole.log(scores.filter(s => s > 50).join(","));`,
  "js:jsarray/4": `const nums = [12, 30, 25];\nconsole.log(nums.reduce((sum, x) => sum + x, 0));`,
  "js:jsarray/5": `const nums = [12, 30, 25];\nconsole.log(nums.find(x => x > 20));\nconsole.log(nums.includes(12));`,
  "js:jsarray/6": `const nums = [30, 5, 100, 12];\nconsole.log(nums.sort((a, b) => a - b).join(","));`,
  "js:jsarray/7": `const orders = [\n  { item: "กาแฟ", price: 50, paid: true },\n  { item: "เค้ก", price: 120, paid: false },\n  { item: "ชุดเซ็ต", price: 300, paid: true }\n];\nconsole.log(orders.filter(o => o.paid).map(o => o.price).reduce((s, p) => s + p, 0));`,

  "js:jsobj/0": `const player = { name: "มะลิ", hp: 100 };\nconsole.log(player.name);\nconsole.log(player.hp);`,
  "js:jsobj/1": `const player = { name: "มะลิ", hp: 100 };\nplayer.level = 5;\nplayer.hp = 80;\nconsole.log(player.hp);\nconsole.log(player.level);`,
  "js:jsobj/2": `const player = {\n  name: "มะลิ",\n  greet() {\n    return \`ฉันคือ \${this.name}\`;\n  }\n};\nconsole.log(player.greet());`,
  "js:jsobj/3": `const player = { name: "มะลิ", hp: 100, level: 5 };\nconsole.log(Object.keys(player).join(","));`,
  "js:jsobj/4": `const students = [\n  { name: "มะลิ", score: 65 },\n  { name: "ฟ้า", score: 80 },\n  { name: "ใบเตย", score: 92 }\n];\nconsole.log(students.filter(s => s.score >= 70).map(s => s.name).join(","));`,
  "js:jsobj/5": `const player = { name: "มะลิ", hp: 100 };\nconst { name, hp } = player;\nconsole.log(\`\${name} \${hp}\`);\nconst copy = { ...player, hp: 50 };\nconsole.log(copy.hp);`,

  "js:jsdom/0": `document.querySelector("#title").textContent = "เปลี่ยนด้วย JavaScript";`,
  "js:jsdom/1": `const box = document.querySelector("#box");\nbox.style.backgroundColor = "tomato";\nbox.style.color = "white";`,
  "js:jsdom/2": `document.querySelector("#card").classList.add("active");`,
  "js:jsdom/3": `const list = document.querySelector("#list");\nconst li = document.createElement("li");\nli.textContent = "รายการใหม่";\nlist.appendChild(li);`,
  "js:jsdom/4": `document.querySelectorAll("#menu li").forEach(li => {\n  li.textContent += " ✓";\n});`,
  "js:jsdom/5": `const pic = document.querySelector("#pic");\npic.src = "new.jpg";\npic.alt = "รูปใหม่";`,
  "js:jsdom/6": `const items = [\n  { name: "กาแฟ", price: 50 },\n  { name: "ชาเย็น", price: 45 }\n];\nconst app = document.querySelector("#app");\nitems.forEach(it => {\n  const p = document.createElement("p");\n  p.className = "item";\n  p.textContent = \`\${it.name} - \${it.price}\`;\n  app.appendChild(p);\n});`,
  "js:jsdom/7": `const items = document.querySelectorAll("#list li");\nitems[items.length - 1].remove();`,

  "js:jsevent/0": `const btn = document.querySelector("#btn");\nbtn.addEventListener("click", () => {\n  document.querySelector("#msg").textContent = "กดแล้ว!";\n});`,
  "js:jsevent/1": `let count = 0;\nconst btn = document.querySelector("#counter");\nbtn.addEventListener("click", () => {\n  count++;\n  btn.textContent = count;\n});`,
  "js:jsevent/2": `const input = document.querySelector("#name");\ninput.addEventListener("input", (e) => {\n  document.querySelector("#preview").textContent = e.target.value;\n});`,
  "js:jsevent/3": `const form = document.querySelector("#form");\nform.addEventListener("submit", (e) => {\n  e.preventDefault();\n  document.querySelector("#result").textContent = document.querySelector("#email").value;\n});`,
  "js:jsevent/4": `const items = document.querySelectorAll("#todo li");\nitems.forEach(li => {\n  li.addEventListener("click", () => {\n    li.classList.add("done");\n  });\n});`,

  "js:jsadv/0": `const text = "  Hello World  ";\nconsole.log(text.trim().toUpperCase());\nconsole.log(text.trim().split(" ").length);`,
  "js:jsadv/1": `const player = { name: "มะลิ", hp: 100 };\nconst s = JSON.stringify(player);\nconst o = JSON.parse(s);\nconsole.log(o.name);`,
  "js:jsadv/2": `try {\n  JSON.parse("ข้อมูลพัง");\n} catch (e) {\n  console.log("ข้อมูลไม่ถูกต้อง");\n}`,
  "js:jsadv/3": `console.log("เริ่ม");\nsetTimeout(() => console.log("ครบเวลา"), 100);`,
  "js:jsadv/4": `function getData() {\n  return Promise.resolve("ข้อมูลมาแล้ว");\n}\nasync function main() {\n  const d = await getData();\n  console.log(d);\n}\nmain();`,
  "js:jsadv/5": `class Hero {\n  constructor(name) {\n    this.name = name;\n  }\n  greet() {\n    return \`ฉันคือ \${this.name}\`;\n  }\n}\nconsole.log(new Hero("มะลิ").greet());`,
  "js:jsadv/6": `class Hero {\n  constructor(name) {\n    this.name = name;\n  }\n}\nclass Mage extends Hero {\n  constructor(name, mana) {\n    super(name);\n    this.mana = mana;\n  }\n  cast() {\n    return \`\${this.name} ร่ายเวท พลัง \${this.mana}\`;\n  }\n}\nconsole.log(new Mage("มะลิ", 50).cast());`
};
