/* หน้าแรกต้องสอดคล้องกับข้อมูลคอร์สทุกจุด: จำนวนภาษา รายชื่อภาษา จำนวนภารกิจ (ไม่มีค่าเขียนตายตัว) */
const fs = require("fs"), path = require("path");
const { COURSES } = require("../verify.js");
const UIKIT = require("../public/ui-kit.js");
const { landingValues, languages } = require("../landing.js");
const vals = landingValues(COURSES, (l, box) => UIKIT.LanguageIcon(l, { box }));
vals.VERSION = 0;
const html = UIKIT.renderPlaceholders(fs.readFileSync(path.join(__dirname, "../public/index.html"), "utf8")).replace(/\{\{(\w+)\}\}/g, (m, k) => (k in vals ? String(vals[k]) : m));
const body = html.replace(/<template[\s\S]*?<\/template>/g, "");
let bad = 0;
const ok = (c, m) => { if (!c) { bad++; console.log("❌ " + m); } };
const langs = languages(COURSES), n = langs.length, total = langs.reduce((a, l) => a + l.stages, 0);
ok(!/\{\{\w+\}\}/.test(body), "มี placeholder ที่ไม่ถูกแทนค่า: " + (body.match(/\{\{\w+\}\}/g) || []).slice(0, 3));
const hero = (body.match(/<p class="landing-sub">([\s\S]*?)<\/p>/) || [])[1] || "";
ok(hero.includes("สำรวจ " + n + " ดาวเคราะห์"), "hero ไม่ได้บอกจำนวนดาว " + n);
for (const l of langs) ok(hero.includes(l.name), "hero ไม่มีชื่อภาษา " + l.name);
const cards = (body.match(/<ul class="land-worlds"[\s\S]*?<\/ul>/) || [""])[0];
ok((cards.match(/<li>/g) || []).length === n, "จำนวนการ์ดภาษา ≠ " + n);
const cardSum = [...cards.matchAll(/ · (\d+) ภารกิจ/g)].reduce((a, m) => a + +m[1], 0);
ok(cardSum === total, "ผลรวมภารกิจในการ์ด " + cardSum + " ≠ " + total);
ok(body.includes(n + " ภาษา " + total + " ภารกิจ"), "หัวข้อรายการภาษาไม่ตรง (" + n + " ภาษา " + total + " ภารกิจ)");
const meta = (html.match(/<meta name="description" content="([^"]*)"/) || [])[1] || "";
ok(meta.includes(total + " ภารกิจ") && meta.includes(n + " ภาษา"), "meta description ไม่ตรง: " + meta.slice(0, 80));
const og = (html.match(/<meta property="og:description" content="([^"]*)"/) || [])[1] || "";
ok(langs.every(l => og.includes(l.name)), "og:description ไม่ครบทุกภาษา: " + og);
const title = (html.match(/<title>([^<]*)<\/title>/) || [])[1] || "";
ok(langs.every(l => title.includes(l.name)), "title ไม่ครบทุกภาษา: " + title);
ok(n === 5 || !/\b5 (ภาษา|ดาว)/.test(body + meta), "ยังมีข้อความ \"5 ภาษา/5 ดาว\" ทั้งที่มี " + n + " ภาษา");
console.log(bad ? "หน้าแรก: พบปัญหา " + bad + " จุด" : "หน้าแรกสอดคล้องกับข้อมูลคอร์ส (" + n + " ภาษา · " + total + " ภารกิจ: " + langs.map(l => l.name + " " + l.stages).join(", ") + ") ✓");
process.exit(bad ? 1 : 0);
